In [2]:
import numpy as np
import numpy.linalg as la
import numdifftools as nd

# Error and big-O

## abs err 

In [ ]:
x = 3000
x0 = 5 * 570
abs_err = np.abs(x - x0)
abs_err

150

## true value from relative 

In [ ]:
rel = 0.1
x0 = 660
x = x0/(1 - rel)
x

733.3333333333334

## relative error bound 

In [ ]:
n = 7
k = n - 1
k

6

## power 

In [ ]:
before = 10
after = 10**5
zhi = 16
zhi / np.log10(after/before)

4.0

## up and down 

In [ ]:
d_base = 193
d_c = 38
d_up = d_base + d_c
d_down = d_base - d_c
s_base = 65
s_c = 2
s_up = s_base + s_c
s_down = s_base - s_c

In [ ]:
np.array([d_up/s_up, d_up/s_down, d_down/s_up, d_down/s_down])*60 - 178

array([ 28.86567164,  42.        , -39.19402985, -30.38095238])

## rel up down 

In [ ]:
i_up = 1.05
i_down = 0.95
r_up = 20*1.03
r_down = 20*0.97
(np.array([i_up * r_up, i_up * r_down, i_down * r_up, i_down * r_down]) - 20)/20

array([ 0.0815,  0.0185, -0.0215, -0.0785])

# Floating point & IEEE

## exact representation

In [ ]:
p = 4
2**p

16

## biggest or smallest positive normal or subnormal

### normal

In [2]:
l,u = -8, 9
p = 5

In [3]:
2**l # smallest

0.00390625

In [ ]:
2**(u+1)*(1-2**(-p)) # biggest

3.3895313892515355e+38

### subnormal

In [ ]:
m = -6

In [ ]:
epsilon*2**m # smallest

0.001953125

## machine epsilon

In [45]:
n = 5 # fraction part
epsilon = 2**(-n)
epsilon

0.03125

## softmax 

In [ ]:
np.log(np.finfo(np.float32).max - np.exp(86.04381) - np.exp(84.14729) - np.exp(86.38088))

88.53038289905838

# rounding

In [19]:
n = 4 # fraction part
eps = 2**(-n)
abs_err_down = 0.046875
abs_err_up = eps - abs_err_down
abs_err_up

0.015625

# Eigenvalues

## eigenvalues of matrix polynomials 

In [46]:
evb = 5
eva = 1/evb + 3
eva

3.2

In [4]:
A = np.array([[17, -8, 11, -3, -4],
              [0, -14, -8, -7, -1],
              [0, 0, 11, 8, -16],
              [0, 0, 0, -5, -13],
              [0, 0, 0, 0, -2],
             ])
eigval = la.eig(A)[0]
print(eigval)
eigval + 4

[ 17. -14.  11.  -5.  -2.]


array([ 21., -10.,  15.,  -1.,   2.])

In [9]:
v = np.array([5, 15, 9])
v / la.norm(v, ord = np.inf)

array([0.33333333, 1.        , 0.6       ])

## normalized iteration

In [ ]:
for i in range(n):
    A = As[i]
    xk = x0/np.linalg.norm(x0,2)
    err = 1
    count = 0
    while(err >= 1e-12):
        last = np.copy(xk)
        yk = A @ xk
        xk = yk/la.norm(yk,2)
        err = la.norm(xk - last, 2)
        count += 1
    cnt.append(count)
    eigenvec1.append(xk)
    eigenval1.append(xk.T@A@xk/(xk.T@xk))

## inverse iteration

In [ ]:
for i in range(n):
    A = As[i]
    xk = x0/np.linalg.norm(x0,2)
    err = 1
    P, L, U = la.lu(A)
    while(err >= 1e-12):
        last = np.copy(xk)
        y = la.solve_triangular(L, np.dot(P.T, xk), lower = True)
        xk = la.solve_triangular(U, y)
        xk = xk/la.norm(xk, 2)
        err = la.norm(xk - last, 2)
    eigenvec2.append(xk)
    eigenval2.append(xk.T@A@xk/(xk.T@xk))

## shifted inverse iteration

In [ ]:
for i in range(n):
    A = As[i] - np.identity(2)
    xk = x0/np.linalg.norm(x0,2)
    P, L, U = la.lu(A)
    for j in range(500):
        y = la.solve_triangular(L, np.dot(P.T, xk), lower = True)
        xk = la.solve_triangular(U, y)
        xk = xk/np.linalg.norm(xk, 2)
    shifted_eigvec.append(xk)
    shifted_eigval.append(xk.T@As[i]@xk/(xk.T@xk))

# sparse

In [48]:
from scipy.sparse import coo_matrix,csr_matrix

## coo construction

In [49]:
data  = np.array([1.20, 1.00, 0.90, 0.40, 0.80])
row = np.array([0, 0, 1, 2, 3])
col = np.array([0, 2, 0, 3, 1])
coo = coo_matrix((data, (row, col)), shape=(4, 4)).toarray()
coo

array([[1.2, 0. , 1. , 0. ],
       [0.9, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.4],
       [0. , 0.8, 0. , 0. ]])

## csr construction

In [26]:
indptr = np.array([0, 2, 5, 7, 7])
indices = np.array([1, 2, 0, 1, 3, 0, 3])
data = np.array([0.40, 0.40, 0.40, 0.90, 0.40, 0.70, 0.20])
csr_matrix((data, indices, indptr), shape=(4, 4)).toarray()

array([[0. , 0.4, 0.4, 0. ],
       [0.4, 0.9, 0. , 0.4],
       [0.7, 0. , 0. , 0.2],
       [0. , 0. , 0. , 0. ]])

## CSR to dense

In [ ]:
def CSR_to_DNS(data, col, rowptr, shape):
    A = np.zeros(shape)
    counter = 0
    row = 0
    for i in range(len(data)):
        while counter >= rowptr[row+1]:
            row += 1
        A[row][col[i]] = data[i]
        counter += 1
    return A

## dense to csr

In [ ]:
def DNS_to_CSR(A):
    data = []
    col = []
    rowptr = [0]
    shape = A.shape
    counter = 0
    for i in range(shape[0]):
        for j in range(shape[1]):
            element = A[i][j]
            if element != 0:
                counter += 1
                data.append(element)
                col.append(j)
        rowptr.append(counter)
    return data, col, rowptr, shape

## dense to coo

In [ ]:
def DNS_to_COO(A):
    data = []
    row = []
    col = []
    shape = A.shape
    for i in range(shape[0]):
        for j in range(shape[1]):
            element = A[i][j]
            if element != 0:
                data.append(element)
                row.append(i)
                col.append(j)
    return data, col, row, shape

## coo to dense

In [ ]:
def COO_to_DNS(data, col, row, shape):
    A = np.zeros(shape)
    for i in range(len(data)):
        A[row[i]][col[i]] = data[i]
    return A

## condition accuracy

In [ ]:
s_t = -4 # solution
t = 3 # cond
s = s_t + t # A, b
s

-1

In [18]:
#s_t = -4 # solution
t = 3 # cond
s = -3 # A, b
s - t

-6

# Monte Carlo

## clay

In [ ]:
import numpy as np
import random

n = 200000
x_min = -5
x_max = 5
y_min = -5
y_max = 5
z_min = 0
z_max = 2
count = 0
for i in range(n):
    x = random.uniform(x_min, x_max)
    y = random.uniform(y_min, y_max)
    z = random.uniform(z_min, z_max)
    fun = f(x, y)
    if z < fun and (x**2+y**2) < 25 and z > 0:
        count += 1
volume = (z_max - z_min) * (x_max - x_min) * (y_max - y_min) * (count / n)

## volume between

In [ ]:
import numpy as np
import random

n = 200000
x_min = -3
x_max = 3
y_min = -3
y_max = 3
z_min = 0
z_max = 2
count = 0
for i in range(n):
    x = random.uniform(x_min, x_max)
    y = random.uniform(y_min, y_max)
    z = random.uniform(z_min, z_max)
    if z >= top(x, y) and z <= bottom(x, y):
        count += 1
volume = (z_max - z_min) * (x_max - x_min) * (y_max - y_min) * (count / n)

# Linear system

## forward

o(n^2)

In [ ]:
import numpy as np
def forward_sub(L, b):
    """x = forward_sub(L, b) is the solution to L x = b
       L must be a lower-triangular matrix
       b must be a vector of the same leading dimension as L
    """
    n = L.shape[0]
    x = np.zeros(n)
    for i in range(n):
        tmp = b[i]
        for j in range(i):
            tmp -= L[i,j] * x[j]
        x[i] = tmp / L[i,i]
    return x


## backward

o(n^2)

In [ ]:
import numpy as np
def back_sub(U, b):
    """x = back_sub(U, b) is the solution to U x = b
       U must be an upper-triangular matrix
       b must be a vector of the same leading dimension as U
    """
    n = U.shape[0]
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        tmp = b[i]
        for j in range(i+1, n):
            tmp -= U[i,j] * x[j]
        x[i] = tmp / U[i,i]
    return x

## solve lu

o(n^2)

In [ ]:
import numpy as np
def lu_solve(L, U, b):
    """x = lu_solve(L, U, b) is the solution to L U x = b
       L must be a lower-triangular matrix
       U must be an upper-triangular matrix of the same size as L
       b must be a vector of the same leading dimension as L
    """
    y = forward_sub(L, b)
    x = back_sub(U, y)
    return x


## find lu

o(n^3)

In [ ]:
import numpy as np
def lu_decomp(A):
    """(L, U) = lu_decomp(A) is the LU decomposition A = L U
       A is any matrix
       L will be a lower-triangular matrix with 1 on the diagonal, the same shape as A
       U will be an upper-triangular matrix, the same shape as A
    """
    n = A.shape[0]
    if n == 1:
        L = np.array([[1]])
        U = A.copy()
        return (L, U)

    A11 = A[0,0]
    A12 = A[0,1:]
    A21 = A[1:,0]
    A22 = A[1:,1:]

    L11 = 1
    U11 = A11

    L12 = np.zeros(n-1)
    U12 = A12.copy()

    L21 = A21.copy() / U11
    U21 = np.zeros(n-1)

    S22 = A22 - np.outer(L21, U12)
    (L22, U22) = lu_decomp(S22)

    L = np.block([[L11, L12], [L21, L22]])
    U = np.block([[U11, U12], [U21, U22]])
    return (L, U)

## solve by lup

In [ ]:
import numpy as np
def lup_solve(L, U, P, b):
    """x = lup_solve(L, U, P, b) is the solution to L U x = P b
       L must be a lower-triangular matrix
       U must be an upper-triangular matrix of the same shape as L
       P must be a permutation matrix of the same shape as L
       b must be a vector of the same leading dimension as L
    """
    z = np.dot(P, b)
    x = lu_solve(L, U, z)
    return x
The number of operations for the LUP solve algorithm is 
O
(
n
2
)
 as 
n
→
∞
.



## find lup

In [ ]:
import numpy as np
def lup_decomp(A):
    """(L, U, P) = lup_decomp(A) is the LUP decomposition P A = L U
       A is any matrix
       L will be a lower-triangular matrix with 1 on the diagonal, the same shape as A
       U will be an upper-triangular matrix, the same shape as A
       U will be a permutation matrix, the same shape as A
    """
    n = A.shape[0]
    if n == 1:
        L = np.array([[1]])
        U = A.copy()
        P = np.array([[1]])
        return (L, U, P)

    i = np.argmax(A[:,0])
    A_bar = np.vstack([A[i,:], A[:i,:], A[(i+1):,:]])

    A_bar11 = A_bar[0,0]
    A_bar12 = A_bar[0,1:]
    A_bar21 = A_bar[1:,0]
    A_bar22 = A_bar[1:,1:]

    S22 = A_bar22 - np.dot(A_bar21, A_bar12) / A_bar11

    (L22, U22, P22) = lup_decomp(S22)

    L11 = 1
    U11 = A_bar11

    L12 = np.zeros(n-1)
    U12 = A_bar12.copy()

    L21 = np.dot(P22, A_bar21) / A_bar11
    U21 = np.zeros(n-1)

    L = np.block([[L11, L12], [L21, L22]])
    U = np.block([[U11, U12], [U21, U22]])
    P = np.block([
        [np.zeros((1, i-1)), 1,                  np.zeros((1, n-i))],
        [P22[:,:(i-1)],      np.zeros((n-1, 1)), P22[:,i:]]
    ])
    return (L, U, P)

## similarity

## find converged vector

In [ ]:
A = np.array([[9, -1], [0, 8]])
X = la.eig(A)[1]
X/la.norm(X, axis=0, ord=np.inf)

(array([9., 8.]),
 array([[1.        , 0.70710678],
        [0.        , 0.70710678]]))

## compute D

In [ ]:
la.inv(X)@A@X

array([[9., 0.],
       [0., 8.]])

# pagerank

## normalize

In [ ]:
M = np.array([x/la.norm(x,1) for x in A.T]).T

In [ ]:
T = np.array([c / la.norm(c, 1) for c in A.T]).T*0.2
for i in range(A.shape[0]):
    T[i][i] = 0.8
x0 = np.zeros(A.shape[0])
x0[2] = 1

last = T@x0
new = T@last
while(not np.array_equal(new, last)):
    last = new
    new = T@last
p = new[4]

In [ ]:
A = A.T
M = np.array([c / la.norm(c, 1) for c in A.T]).T

x0 = np.zeros(8)
x0[2] = 1

last = M@x0
new = M@last
while(not np.array_equal(new, last)):
    last = new
    new = M@last
prob = new[0]

In [ ]:
C = np.array([
    [0, 0, 1, 1, 0],
    [1, 0, 0, 0, 1],
    [0, 1, 0, 1, 1],
    [1, 1, 1, 0, 0],
    [1, 0, 0, 0, 0],
])

C = np.array([c / la.norm(c, 1) for c in C.T]).T

x0 = [1, 0, 0, 0, 0]
last = C@x0
new = C@last

while(not np.array_equal(last, new)):
    last = new
    new = C@last
    
p = new[3]

# finite difference

In [43]:
h = 0.1
x = np.array([1.0, 1.0, 1.0])
def f(t):
    x, y, z = t
    return x*y*z+x+1

In [21]:
# forward nd
approx = np.zeros_like(x)
for i in range(x.shape[0]):
    xfd = x.copy()
    print(xfd)
    xfd[i] += h
    print(h)
    print(xfd[i])
    approx[i] = (f(xfd) - f(x)) / h
    print(approx[i])
approx

[1. 1. 1.]
0.1
1.1
2.0000000000000018
[1. 1. 1.]
0.1
1.1
1.0000000000000009
[1. 1. 1.]
0.1
1.1
1.0000000000000009


array([2., 1., 1.])

In [ ]:
# forward 1d Oh 1 eval
appro = (f(x + h) - f(x)) / h
appro

In [44]:
# forward nd
approx = np.zeros_like(x)
for i in range(x.shape[0]):
    xfd = x.copy()
    xfd[i] += h
    approx[i] = (f(xfd) - f(x)) / h
approx

array([2., 1., 1.])

In [ ]:
# backward 1d Oh 1 eval
appro = (f(x) - f(x - h)) / h
appro

7.8051

In [ ]:
# backward nd
approx = np.zeros_like(x)
for i in range(x.shape[0]):
    xfd = x.copy()
    xfd[i] -= h
    approx[i] = (f(x) - f(xfd)) / h
approx

array([2.9, 1. , 4.8])

In [ ]:
x = np.array([1, 1, 1], dtype = float)
h = 0.1
def f(inp):
    x, y, z = inp
    return x + 2
approx = np.zeros_like(x)
for i in range(x.shape[0]):
    xfd1 = x.copy()
    xfd2 = x.copy()
    xfd1[i] += h
    xfd2[i] -= h
    approx[i] = (f(xfd1) - f(xfd2)) / (2*h)
approx

array([1., 0., 0.])

In [37]:
# central 1d Oh^2 2 eval
appro = (f(t + h) - f(t - h)) / (2 * h)
appro

1.2227060047378822

In [ ]:
# central nd
approx = np.zeros_like(x)
for i in range(x.shape[0]):
    xfd1 = x.copy()
    xfd2 = x.copy()
    xfd1[i] += h
    xfd2[i] -= h
    approx[i] = (f(xfd1) - f(xfd2)) / (2*h)

# Nonlinear

## jacobian

In [ ]:
def f(inp):
    x, y = inp
    return np.array([
        x+5,
        4*x**2+y-5
    ])
x0=[1, -1]
j = nd.Jacobian(f)(x0)
j

array([[1., 0.],
       [8., 1.]])

In [ ]:
x1 = x0 - la.inv(j)@f(x0)
x1

array([-5., 49.])

## hessian

In [7]:
def f(inp):
    x, y = inp
    return 5*x**3+4*y**4
x0 = [2, 3]
h = nd.Hessian(f)(x0)
h

array([[6.00000000e+01, 3.45710903e-14],
       [3.45710903e-14, 4.32000000e+02]])

## Newton Method

2 evals; typically; quadratic convergence depends on initial guess; start point; when diff too costly try secant

$x_{k+1} = x_k + h = x_k - \frac{f(x_k)}{f'(x_k)}$

In [ ]:
# root
def f(x):
    return -1 * np.exp(-1 * x**2)

root = 0.3 - f(0.3) / nd.Gradient(f)(0.3)
root

1.96666666666671

In [ ]:
# high dimension
def f(x1, x2):
    return np.array([3*x1*x2+6, x1**3+x2**2+5])

# A function that returns the Jacobian may be useful
def J(x,y):
    return np.array([[3 * x ** 2, -2 * y], [1 + 2*x*y, x**2]])
 
x = np.copy(xi)
res = la.norm(f(x[0], x[1]), 2)

while res >= tol:
    x = x - la.inv(J(x[0], x[1]))@f(x[0], x[1])
    res = la.norm(f(x[0], x[1]), 2)
    
root = x

In [50]:
x0 = [-2, 2]
def f(inp):
    x1, x2 = inp
    return np.array([3*x1*x2+6, x1**3+x2**2+5])
j = nd.Jacobian(f)(x0)
j

array([[ 6., -6.],
       [12.,  4.]])

In [51]:
x1 = x0 - la.inv(j)@f(x0)
x1

array([-1.8125,  1.1875])

In [ ]:

def f(x,y):
    return np.array([x**3 - y**2, x+y*x**2 - 2])

# A function that returns the Jacobian may be useful
def J(x,y):
    return np.array([[3 * x ** 2, -2 * y], [1 + 2*x*y, x**2]])
 
x = np.copy(xi)
res = la.norm(f(x[0], x[1]), 2)

while res >= tol:
    x = x - la.inv(J(x[0], x[1]))@f(x[0], x[1])
    res = la.norm(f(x[0], x[1]), 2)
    
root = x

x0 = [1, -1]
def f(inp):
    x, y = inp
    return np.array([5*x**4 + 3*y**3 - 6, 4*x**2+2*y - 5])
j = nd.Jacobian(f)(x0)
j

x1 = x0 - la.inv(j)@f(x0)
x1

## Bisection Method

1 evaluation each iteration; linear convergence: 1/2; f is continuous and f(a) and f(b) opposite

In [ ]:
# root
opt.bisect(f, a = -4, b = 1, maxiter = 2, disp = False)

In [ ]:
import numpy as np

def f(x):
    return get_temperature(x) - 375
    
intervals = []
a = 0
fa = f(a)
b = max_wood
fb = f(b)
interval = (a, b)
intervals.append(interval)
m = (a + b) / 2
fm = f(m)


while (np.abs(fm) >= epsilon):
    if (fm * fb > 0):
        b = m
        fb = fm
    elif (fm * fa > 0):
        a = m
        fa = fm
    interval = (a, b)
    intervals.append(interval)
    m = (a + b) / 2
    fm = f(m)



weight = m
    

# error prediction

In [ ]:
i = 0
err = 0.3
rate = 0.2
while err >= 1e-4:
    err *= rate
    i+=1
i

5

# Secant Method

local convergence 1.618; 1 eval; two staring guess; superlinear

$f'(x_k) = \frac{f(x_k) - f(x_{k-1})}{x_k - x_{k-1}}$

$x_{k+1} = x_k + h = x_k - \frac{f(x_k)}{f'(x_k)}$

In [ ]:
# estimation of derivative
(f(0) - f(-2)) / 2

In [ ]:
import numpy as np
roots = []

x1, x2 = xks

def slp(f, x2, x1):
    return (f(x2) - f(x1)) / (x2 - x1)
   
last2 = x2
last1 = x1
for i in range(5):
    cur = last2 - f(last2)/slp(f, last2, last1)
    roots.append(cur)
    last1 = last2
    last2 = cur
    
roots = np.array(roots)

# Optimization (1d)

1d: 1st d = 0; 2nd d > 0

# Newton

$x_{k+1} = x_k + h = x_k - \frac{f'(x_k)}{f''(x_k)}$

In [ ]:
# root
def f(x):
    return 6*x**4+2*y**2
def fp(x):
    return 2*x * np.exp(-1 * x**2)
root = opt.newton(f, fprime = fp, x0=0.3, maxiter = 2, disp = False)
root

2.2209039548022598

In [33]:
def f(inp):
    x, y = inp
    return 5*x**3+4*y**4
x0 = np.array([2 , 3])
print(nd.Hessian(f)(x0))
s = - nd.Gradient(f)(x0) / nd.Hessian(f)(x0)
s

[[6.00000000e+01 3.45710903e-14]
 [3.45710903e-14 4.32000000e+02]]


array([[-1.00000000e+00, -1.24959900e+16],
       [-1.73555417e+15, -1.00000000e+00]])

# Golden section

1 eval; linearly convergent; 

In [ ]:
import numpy as np

def f(x):
    return (x - 3.2)**2
a = -1
b = 8

gs = (np.sqrt(5) - 1) / 2
m1 = a + (1 - gs) * (b - a)
m2 = a + gs * (b - a)
epsilon = 1e-5

# Begin your modifications below here
f1 = f(m1)
f2 = f(m2)
h = b-a

while h >= epsilon:
    
    if f1 > f2:
        a = m1
        m1 = m2
        f1 = f2
        h *= gs
        m2 = a + gs * h
        f2 = f(m2)
    else:
        b = m2
        m2 = m1
        f2 = f1
        h *= gs
        m1 = a + (1 - gs) * h
        f1 = f(m1)
    break
print(a)
print(b)

# End your modifications above here

-1
4.562305898749054


In [ ]:
gs = (np.sqrt(5) - 1) / 2
22 * (gs**3)

5.193495504995375

# Optimization (nd)

nd: grad = 0; H positive definite

# Steepest Descent

linear convergent

In [ ]:
import numpy.linalg as la
import scipy.optimize as opt
import numpy as np

def obj_func(alpha, x, s):
    # code for computing the objective function at (x+alpha*s)
    return f_of_x_plus_alpha_s

def gradient(inpu):
    # code for computing gradient
    x, y = inpu
    return np.array([x/4 - np.cos(x)*np.cos(y / np.sqrt(2)), 
                    y/4 + 1 / np.sqrt(x) * np.sin(x)*np.sin(y / np.sqrt(2))])

def steepest_descent(x_init):
    x_new = x_init
    x_prev = np.random.randn(x_init.shape[0])
    while(la.norm(x_prev - x_new) > 1e-6):
        x_prev = x_new
        s = -gradient(x_prev)
        alpha = opt.minimize_scalar(obj_func, args=(x_prev, s)).x
        x_new = x_prev + alpha*s

In [ ]:
def f(inp):
    x, y = inp
    return 2 * x**2 + 14 * x* y + 2 * y**2 + 10 * np.sin(y)**2 + 4 * np.cos(x * y)

In [ ]:
x0 = [-4, 2]
s0 = -1 * nd.Gradient(f)(x0)
s0

array([-19.91486597,  71.3977569 ])

In [ ]:
x1 = x0 + 0.05 * s0
x1

array([-4.9957433 ,  5.56988784])

# Newton's method 

In [ ]:
import numpy as np
import numpy.linalg as la
import scipy.optimize as opt
def f(r):
    x, y = r
    return 3 +((x**2)/8) + ((y**2)/8) - np.sin(x)*np.cos((2**-0.5)*y)
    
def gradient(inpu):
    # code for computing gradient
    x, y = inpu
    return np.array([x/4 - np.cos(x)*np.cos(y / np.sqrt(2)), 
                    y/4 + 1 / np.sqrt(x) * np.sin(x)*np.sin(y / np.sqrt(2))])
                    
def hessian(inpu):
    x, y = inpu
    return np.array([[np.sin(x)*np.cos(y/np.sqrt(2)) + 1/4,
        np.cos(x)*np.sin(y / np.sqrt(2))/np.sqrt(2)], 
    [np.cos(x)*np.sin(y / np.sqrt(2))/np.sqrt(2),
    np.sin(x)*np.cos(y/np.sqrt(2)) + 1/4]])
    
def newtons(x_init, stop):
    count = 0
    x_new = x_init
    x_prev = np.random.randn(x_init.shape[0])
    while(la.norm(x_prev-x_new)>stop):
        x_prev = x_new
        s = -la.solve(hessian(x_prev), gradient(x_prev))
        x_new = x_prev + s
        count += 1
    return x_new, count
    
def steepest_descent(x_init, stop):
    count = 0
    x_new = x_init
    x_prev = np.random.randn(x_init.shape[0])
    while(la.norm(x_prev - x_new) > stop):
        x_prev = x_new
        s = -gradient(x_prev)
        alpha = opt.minimize_scalar(f, args=(x_prev, s)).x
        x_new = x_prev + alpha*s
        count += 1
    return x_new, count
    
r_newton, iteration_count_newton = newtons(r_init, stop)
r_sd, iteration_count_sd = steepest_descent(r_init, stop)



In [59]:
def f(inp):
    x, y = inp
    return 5*x**3+4*y**4

In [60]:
x0 = np.array([2, 3])
h = nd.Hessian(f)(x0)
g = nd.Gradient(f)(x0)
h

array([[6.00000000e+01, 3.45710903e-14],
       [3.45710903e-14, 4.32000000e+02]])

In [61]:
s = -la.solve(h, g)
s

array([-1., -1.])

# SVD

In [ ]:
sig_inv = la.inv(np.diag(sigma))
x = left_multiply_with_V(sig_inv@right_multiply_with_U(b.T).T)

## low rank approximation

In [ ]:
k = 2
u[:, :k]@s[:2]@vt[:2]

## pseudoinverse

In [ ]:
m = U.shape[1]
n = Vh.shape[0]
sig = np.zeros((m, n))
for i, s in enumerate(S):
    sig[i][i] = s if s!=0 else 0
sig_plus = sig.T
A_plus = Vh.T@sig_plus@U.T

## solve

In [ ]:
m = U.shape[1]
n = Vh.shape[0]
sig = np.zeros((m, n))
for i, s in enumerate(S):
    sig[i][i] = s if s!=0 else 0
sig_plus = sig.T
x = Vh.T@sig_plus@U.T@b

## least square by svd

In [15]:
u = np.array([[0, 1, 0, 0],
              [1, 0, 0, 0],
              [0, 0, 0, 1],
              [0, 0, 1, 0]])
sig = np.array([[8, 0, 0],
                [0, 13, 0],
                [0, 0, 0],
                [0, 0, 0]])
vt = np.array([[1/np.sqrt(2),1/np.sqrt(2),0], 
               [1/np.sqrt(2),-1/np.sqrt(2),0], 
               [0, 0, 1]])
b = np.array([12, 3, 12, 4])
x = vt.T@la.pinv(sig)@u.T@b
x

array([ 0.91787899, -0.38754891,  0.        ])

## singular values for pca mean 

In [39]:
import numpy as np

X = np.array([[-1.879, -2.188, 1.129], [-0.030, 1.287, 1.134], [-0.049, 0.299, 1.041], [0.625, 0.339, 2.734]])

In [40]:
X_z = X - np.mean(X, axis = 0)
X_z

array([[-1.54575, -2.12225, -0.3805 ],
       [ 0.30325,  1.35275, -0.3755 ],
       [ 0.28425,  0.36475, -0.4685 ],
       [ 0.95825,  0.40475,  1.2245 ]])

In [41]:
u, s, vt = la.svd(X_z)

In [42]:
s

array([3.12582776, 1.49271901, 0.34168884])

## number of components pca

In [53]:
import numpy as np

U = np.array([[0.0, 0.0, -0.2, -0.3, 0.0, -0.3, -0.1, -0.1, -0.1], [-0.5, -0.4, 0.1, 0.0, -0.1, -0.3, 0.2, 0.1, 0.3], [0.3, 0.2, -0.3, -0.1, -0.2, 0.3, -0.1, -0.2, 0.5], [-0.1, -0.2, 0.1, 0.0, 0.0, 0.0, 0.2, -0.5, -0.2], [0.1, -0.1, 0.3, 0.0, -0.5, 0.1, 0.1, 0.2, 0.0], [-0.1, 0.5, 0.3, -0.5, -0.4, -0.1, -0.1, 0.1, -0.1], [0.2, -0.3, 0.3, -0.1, -0.2, -0.1, -0.5, -0.3, -0.3], [0.2, 0.2, -0.2, -0.2, 0.1, -0.2, 0.1, -0.2, 0.2], [-0.1, 0.0, -0.3, 0.3, -0.6, 0.2, 0.1, -0.1, -0.3], [-0.1, 0.5, 0.2, 0.2, 0.3, 0.1, 0.4, -0.2, -0.3], [0.2, -0.3, 0.2, 0.1, -0.1, -0.1, 0.1, -0.3, 0.3], [-0.3, 0.2, 0.1, 0.2, 0.1, 0.1, -0.4, 0.1, 0.3], [0.3, -0.1, 0.2, -0.4, 0.1, 0.3, 0.4, 0.2, 0.0], [-0.1, -0.1, 0.3, -0.1, -0.1, 0.2, 0.1, 0.1, -0.1], [-0.3, 0.2, 0.3, -0.1, -0.2, -0.1, 0.2, -0.4, 0.3], [0.4, 0.2, 0.1, 0.4, -0.1, -0.6, 0.1, 0.2, 0.1], [0.1, 0.0, 0.5, 0.3, 0.1, 0.3, -0.3, 0.0, 0.1]])
S = np.array([[39,  0,  0,  0,  0,  0,  0,  0,  0], [ 0, 37,  0,  0,  0,  0,  0,  0,  0], [ 0,  0, 31,  0,  0,  0,  0,  0,  0], [ 0,  0,  0, 24,  0,  0,  0,  0,  0], [ 0,  0,  0,  0, 17,  0,  0,  0,  0], [ 0,  0,  0,  0,  0, 13,  0,  0,  0], [ 0,  0,  0,  0,  0,  0, 12,  0,  0], [ 0,  0,  0,  0,  0,  0,  0,  6,  0], [ 0,  0,  0,  0,  0,  0,  0,  0,  1]])
V = np.array([[-0.2, 0.4, -0.1, -0.2, 0.8, -0.1, -0.1, -0.2, 0.0], [0.4, -0.2, -0.1, 0.1, 0.4, -0.4, 0.1, 0.5, -0.6], [-0.1, -0.5, -0.7, -0.4, 0.1, 0.1, -0.2, 0.0, 0.1], [0.0, 0.4, -0.3, -0.3, -0.4, -0.2, 0.4, -0.4, -0.4], [-0.7, 0.0, 0.0, 0.0, -0.1, -0.4, 0.3, 0.5, 0.2], [0.1, 0.0, -0.4, 0.7, 0.0, -0.5, -0.1, -0.3, 0.3], [-0.1, 0.3, 0.0, -0.1, -0.3, -0.3, -0.8, 0.2, -0.1], [0.0, -0.5, 0.5, -0.3, 0.0, -0.5, -0.1, -0.4, 0.0], [0.5, 0.3, -0.1, -0.4, 0.0, -0.2, 0.2, 0.2, 0.6]])

In [54]:
var = S.T@S
per = 0.77
thrs = np.sum(var) * per
i = 1
while i < var.shape[1]:
    if np.sum(var[:, :i]) >= thrs:
        break
    i += 1
i

4

# least square

## solve

In [ ]:
x = la.inv(A.T@A)@A.T@b

## error

In [ ]:
r = 2

In [18]:
la.norm(u.T[:, r:]@b[r:], r) # utb

12.649110640673518


## rank from data pts 

In [ ]:
data_pts = [6.0, 10.5, 5.0, 9.5, 5.0, 11.0, 10.5, 12.0, 12.0, 11.5]
unq_pts = len(set(data_pts)) # number of unique data pts
num_items = 7 # number of items
min(num_items, unq_pts)

5

## max coefficient 

In [55]:
data_pts = [6.5, 8.0, 11.5, 9.0, 6.5]
unq_pts = len(set(data_pts))
unq_pts

4

In [ ]:
x = 2
15*x**2+12*x+2

86

In [24]:
e = 0.2435
i = 0
while e >= 1e-3:
    e /= 2
    i += 1
i

8

In [62]:
def f(x):
    return 12*x**2+12*x+7
f(3)

151

In [38]:
1./np.array([0, 1, 2])

<ipython-input-38-f754275d76ed>:1: RuntimeWarning: divide by zero encountered in true_divide
  1./np.array([0, 1, 2])


array([inf, 1. , 0.5])