In [55]:
import numpy as np

In [56]:
def graph_to_Gmat(g, damping_factor):
    Gmat = np.zeros(g.shape)
    for i in range(g.shape[0]):
        for j in range(g.shape[1]):
            if np.sum(g[:,j]) == 0:
                Gmat[i][j] = 1/g.shape[0]
            else:
                Gmat[i][j] = (1-damping_factor)/g.shape[1]+damping_factor/np.sum(g[:,j])*g[i][j]
    return Gmat

In [59]:
# Test case: Node with no out
g = np.array([
    [0, 1, 1, 0],
    [1, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 1, 0]
])
a = 0.85
expected = np.array([
    [0.0375, 0.8875, 0.4625, 0.25],
    [0.8875, 0.0375, 0.0375, 0.25],
    [0.0375, 0.0375, 0.0375, 0.25],
    [0.0375, 0.0375, 0.4625, 0.25]
], dtype='float32')
actual = np.array(graph_to_Gmat(g, a), dtype='float32')
assert np.array_equal(expected, actual)

In [60]:
# Test case: Node with no out
g = np.array([
    [0, 1, 1, 1],
    [0, 0, 1, 1],
    [1, 1, 0, 0],
    [1, 1, 0, 0]
])
a = 0.9
expected = np.array([
    [0.025, 0.325, 0.475, 0.475],
    [0.025, 0.025, 0.475, 0.475],
    [0.475, 0.325, 0.025, 0.025],
    [0.475, 0.325, 0.025, 0.025]
], dtype='float32')
actual = np.array(graph_to_Gmat(g, a), dtype='float32')
assert np.array_equal(expected, actual)

In [61]:
graph = np.array([
    [0, 1, 0, 0],
    [1, 0, 0, 1],
    [0, 0, 0, 0],
    [1, 1, 0, 0]
])
a = 0.8
print(graph_to_Gmat(graph, a))

[[0.05 0.45 0.25 0.05]
 [0.45 0.05 0.25 0.85]
 [0.05 0.05 0.25 0.05]
 [0.45 0.45 0.25 0.05]]
