Actually this is not PCA, but PCA-related questions in CS357.

In [30]:
import numpy as np
import numpy.linalg as la

In [31]:
def center_data(A):
    '''
    Given a matrix A, we want every column to shift by their column mean
    '''
    B = np.copy(A).astype(float)
    for i in range(B.shape[1]):
        B[:,i] -= np.mean(B[:,i])
    return B

In [32]:
# Generic Test Case for center_data
X = np.array([[0.865, 1.043, -0.193], [-1.983, -1.250, 2.333], [0.305, 1.348, -0.024], [1.509, -0.069, -1.400]])
expected = np.array([
    [ 0.691,  0.775, -0.372],
    [-2.157, -1.518,  2.154],
    [ 0.131,  1.08 , -0.203],
    [ 1.335, -0.337, -1.579]
])
actual = center_data(X)
tol = 10**-4
assert la.norm(expected-actual) < tol

In [33]:
def pc_needed(U, S, V, limit):
    '''
    Given a singular value decomposition
    return the number of principal components needed to
    achieve a variance coverage equal to or higher than limit
    '''
    var = S@S / np.sum(S@S)
    curr = 0.0
    counter = 0
    for i in range(len(S)):
        if curr >= limit:
            break
        curr += var[i,i]
        counter += 1
    return counter

In [34]:
# Generic Test Case for pc_needed
limit = 0.57
U = np.array([[-0.1, 0.1, -0.1, -0.1, -0.1, 0.0, -0.3, 0.0, -0.6], [0.1, -0.5, 0.1, 0.1, 0.2, 0.1, -0.4, 0.2, 0.0], [0.2, 0.2, -0.1, 0.7, 0.3, -0.1, 0.3, 0.1, -0.4], [0.1, -0.1, -0.2, 0.0, -0.1, 0.0, 0.2, 0.1, 0.2], [-0.2, 0.0, -0.1, 0.4, -0.1, -0.2, -0.4, 0.1, 0.4], [0.1, -0.3, -0.1, -0.2, 0.2, -0.3, 0.0, 0.1, 0.0], [-0.4, 0.2, 0.0, -0.1, 0.2, 0.4, -0.3, 0.2, -0.1], [0.2, -0.3, -0.3, -0.2, 0.4, -0.2, 0.0, 0.1, 0.1], [0.6, 0.3, -0.2, 0.0, -0.2, 0.1, -0.3, 0.1, 0.1], [0.0, -0.1, 0.1, -0.3, -0.4, -0.2, 0.2, 0.5, -0.1], [-0.4, 0.1, -0.2, 0.0, 0.1, 0.0, 0.2, 0.4, 0.1], [0.3, 0.2, 0.3, -0.2, 0.3, 0.1, -0.1, 0.3, -0.1], [0.3, 0.2, 0.2, -0.2, -0.1, 0.0, 0.0, -0.4, 0.1], [-0.2, 0.0, 0.3, -0.2, 0.4, -0.4, 0.0, -0.2, 0.0], [-0.1, 0.3, -0.4, -0.1, -0.1, -0.4, -0.1, -0.1, -0.2], [0.0, 0.0, -0.6, -0.2, 0.2, 0.4, 0.1, -0.2, 0.0], [0.0, 0.0, -0.1, 0.0, -0.1, -0.4, -0.4, -0.1, -0.2], [-0.1, -0.5, 0.1, 0.1, -0.2, 0.2, 0.0, -0.3, -0.3]])
S = np.array([[39,  0,  0,  0,  0,  0,  0,  0,  0], [ 0, 36,  0,  0,  0,  0,  0,  0,  0], [ 0,  0, 32,  0,  0,  0,  0,  0,  0], [ 0,  0,  0, 25,  0,  0,  0,  0,  0], [ 0,  0,  0,  0, 24,  0,  0,  0,  0], [ 0,  0,  0,  0,  0, 23,  0,  0,  0], [ 0,  0,  0,  0,  0,  0, 17,  0,  0], [ 0,  0,  0,  0,  0,  0,  0, 12,  0], [ 0,  0,  0,  0,  0,  0,  0,  0,  6]])
V = np.array([[-0.5, -0.1, 0.6, 0.1, -0.2, 0.2, 0.5, -0.2, -0.1], [0.2, -0.1, 0.2, -0.5, -0.7, -0.4, 0.0, 0.0, 0.1], [0.0, -0.5, 0.1, 0.4, -0.1, 0.1, -0.3, -0.3, 0.6], [-0.5, 0.6, -0.3, 0.3, -0.2, -0.3, 0.0, 0.0, 0.3], [-0.1, -0.2, -0.7, -0.1, -0.3, 0.2, 0.3, -0.4, -0.2], [0.3, -0.1, 0.0, 0.0, 0.4, -0.3, 0.7, -0.2, 0.4], [0.1, -0.3, 0.0, 0.6, -0.1, -0.5, 0.0, 0.0, -0.5], [0.0, 0.2, 0.2, -0.2, 0.3, -0.2, -0.3, -0.8, -0.2], [0.6, 0.5, 0.1, 0.4, -0.3, 0.3, 0.1, -0.2, 0.0]])
expected = 3
actual = pc_needed(U, S, V, 0.57)
assert expected == actual

In [37]:
def singular_values_for_pca_mean(X):
    '''
    Designed specifically for exam quesiton
    "Singular Values for PCA Mean"
    '''
    X_zeroed = center_data(X)
    U, S, Vh = la.svd(X_zeroed)
    return X_zeroed, S[-1]

In [35]:
# Workspace
A = np.array([[9, -4], [0, 5]])
v, w = la.eig(A)
w

array([[1.        , 0.70710678],
       [0.        , 0.70710678]])

In [39]:
# Workspace 2
X = np.array([[-0.691, 0.721, 0.791], [-1.418, -0.410, 0.600], [0.834, 1.832, 0.013], [0.732, -0.882, -0.885]])
mat, sca = singular_values_for_pca_mean(X)
print(mat)
print(sca)

[[-0.55525  0.40575  0.66125]
 [-1.28225 -0.72525  0.47025]
 [ 0.96975  1.51675 -0.11675]
 [ 0.86775 -1.19725 -1.01475]]
0.14317511289838647
