In [2]:
import numpy as np
import numpy.linalg as la

In [4]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
x, v = la.eig(A)
print(x)
print(v)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [5]:
def power_iteration(A, err_bound, init):
    x_prev = init - 1
    x_post = init
    while (la.norm(x_prev-x_post, 2) >= err_bound):
        x_prev = x_post
        x_post = A@x_post
        x_post /= la.norm(x_post, 2)
    return x_post

In [8]:
err_bound = 10**-12
init = np.ones(3) * -1
print(power_iteration(A, err_bound, init))

[-0.23197069 -0.52532209 -0.8186735 ]
