In [1]:
import numpy as np
import scipy.optimize as opt
import numdifftools as nd
import numpy.linalg as la

# Finite Difference gradient

In [52]:
h = 0.1
x = np.array([1.0, 1.0, 1.0])
def f(inp):
    x, y, z = inp
    return (x**2) * (y**2) * z + x * (y**2) * (z**2) + x * z
# forward nd
approx = np.zeros_like(x)
for i in range(x.shape[0]):
    xfd = x.copy()
    print(xfd)
    xfd[i] += h
    print(h)
    print(xfd[i])
    approx[i] = (f(xfd) - f(x)) / h
    print(approx[i])

[1. 1. 1.]
0.1
1.1
4.100000000000006
[1. 1. 1.]
0.1
1.1
4.200000000000004
[1. 1. 1.]
0.1
1.1
4.100000000000006


In [ ]:
# forward 1d Oh 1 eval
appro = (f(x + h) - f(x)) / h
appro

In [45]:
# forward nd
approx = np.zeros_like(x)
for i in range(x.shape[0]):
    xfd = x.copy()
    xfd[i] += h
    approx[i] = (f(xfd) - f(x)) / h
-1 * approx

array([0, 0, 0])

In [ ]:
# backward 1d Oh 1 eval
appro = (f(x) - f(x - h)) / h
appro

In [ ]:
# backward nd
approx = np.zeros_like(x)
for i in range(x.shape[0]):
    xfd = x.copy()
    xfd[i] -= h
    approx[i] = (f(x) - f(xfd)) / h

In [10]:
x = np.array([1, 1, 1], dtype = float)
h = 0.1
def f(inp):
    x, y, z = inp
    return x + 2
approx = np.zeros_like(x)
for i in range(x.shape[0]):
    xfd1 = x.copy()
    xfd2 = x.copy()
    xfd1[i] += h
    xfd2[i] -= h
    approx[i] = (f(xfd1) - f(xfd2)) / (2*h)
approx

array([1., 0., 0.])

In [ ]:
# central 1d Oh^2 2 eval
appro = (f(x + h) - f(x - h)) / (2 * h)
appro

In [ ]:
# central nd
approx = np.zeros_like(x)
for i in range(x.shape[0]):
    xfd1 = x.copy()
    xfd2 = x.copy()
    xfd1[i] += h
    xfd2[i] -= h
    approx[i] = (f(xfd1) - f(xfd2)) / (2*h)

## Gradient

In [ ]:
g = nd.Gradient(f)([1, 2])

## Jacobian

In [26]:
def f(inp):
    x, y = inp
    return np.array([
        5*x**2 + 4*y**3 - 6,
        6*x**4 + 3*y - 5
    ])
    

In [28]:
j = nd.Jacobian(f)([-1, 0])
j

array([[-10.,   0.],
       [-24.,   3.]])

In [29]:
s = la.solve(j, - f([-1, 0]))
[-1, 0] + s

array([-1.1       , -1.13333333])

## Hessian

In [ ]:
h = nd.Hessian(f)([1, 2])

In [ ]:
x = [1, 2]
s = -la.solve(h, g)
x + s

# Bisection Method

1 evaluation each iteration; linear convergence: 1/2; f is continuous and f(a) and f(b) opposite

In [ ]:
# root
opt.bisect(f, a = -4, b = 1, maxiter = 2, disp = False)

In [ ]:
import numpy as np

def f(x):
    return get_temperature(x) - 375
    
intervals = []
a = 0
fa = f(a)
b = max_wood
fb = f(b)
interval = (a, b)
intervals.append(interval)
m = (a + b) / 2
fm = f(m)


while (np.abs(fm) >= epsilon):
    if (fm * fb > 0):
        b = m
        fb = fm
    elif (fm * fa > 0):
        a = m
        fa = fm
    interval = (a, b)
    intervals.append(interval)
    m = (a + b) / 2
    fm = f(m)



weight = m
    

# Newton Method

2 evals; typically; quadratic convergence depends on initial guess; start point; when diff too costly try secant

## root 

$x_{k+1} = x_k + h = x_k - \frac{f(x_k)}{f'(x_k)}$

In [23]:
# root
def f(x):
    return -1 * np.exp(-1 * x**2)

root = 0.3 - f(0.3) / nd.Gradient(f)(0.3)
root

1.96666666666671

In [ ]:
root -= f(root)/nd.Gradient(f)(root)
root

In [ ]:
import numpy as np
import numpy.linalg as la
import scipy.optimize as opt

def f(x,y):
    return np.array([x**3 - y**2, x+y*x**2 - 2])

# A function that returns the Jacobian may be useful
def J(x,y):
    return np.array([[3 * x ** 2, -2 * y], [1 + 2*x*y, x**2]])
 
x = np.copy(xi)
res = la.norm(f(x[0], x[1]), 2)

while res >= tol:
    x = x - la.inv(J(x[0], x[1]))@f(x[0], x[1])
    res = la.norm(f(x[0], x[1]), 2)
    
root = x

In [6]:
x0 = [1, -1]
def f(inp):
    x, y = inp
    return np.array([5*x**4 + 3*y**3 - 6, 4*x**2+2*y - 5])
j = nd.Jacobian(f)(x0)
j

array([[20.,  9.],
       [ 8.,  2.]])

In [7]:
x1 = x0 - la.inv(j)@f(x0)
x1

array([ 1.59375, -1.875  ])

# Secant Method

local convergence 1.618; 1 eval; two staring guess; superlinear

$f'(x_k) = \frac{f(x_k) - f(x_{k-1})}{x_k - x_{k-1}}$

$x_{k+1} = x_k + h = x_k - \frac{f(x_k)}{f'(x_k)}$

In [ ]:
# estimation of derivative
(f(0) - f(-2)) / 2

In [ ]:
import numpy as np
roots = []

x1, x2 = xks

def slp(f, x2, x1):
    return (f(x2) - f(x1)) / (x2 - x1)
   
last2 = x2
last1 = x1
for i in range(5):
    cur = last2 - f(last2)/slp(f, last2, last1)
    roots.append(cur)
    last1 = last2
    last2 = cur
    
roots = np.array(roots)

In [30]:
def f(x):
    return x**3 - 3*x - 7
def slp(f, x1, x0):
    return (f(x1) - f(x0)) / (x1 - x0)

In [31]:
slp(f, 0, -1)

-2.0

In [32]:
x1 = 0

In [33]:
x2 = x1 - f(x1) / (-2)
x2

-3.5

# Optimization (1d)

1d: 1st d = 0; 2nd d > 0

# Newton

$x_{k+1} = x_k + h = x_k - \frac{f'(x_k)}{f''(x_k)}$

In [37]:
# root
def f(x):
    return -1 * np.exp(-1 * x**2)
def fp(x):
    return 2*x * np.exp(-1 * x**2)
root = opt.newton(f, fprime = fp, x0=0.3, maxiter = 2, disp = False)
root

2.2209039548022598

In [8]:
def f(x):
    return 2 * np.sin(x**3)
x0 = 0.45
x1 = x0 - nd.Gradient(f)(x0) / nd.Hessian(f)(x0)
x1

array([[0.22215415]])

# Golden section

1 eval; linearly convergent; 

In [9]:
import numpy as np

def f(x):
    return (x - 3.2)**2
a = -1
b = 8

gs = (np.sqrt(5) - 1) / 2
m1 = a + (1 - gs) * (b - a)
m2 = a + gs * (b - a)
epsilon = 1e-5

# Begin your modifications below here
f1 = f(m1)
f2 = f(m2)
h = b-a

while h >= epsilon:
    
    if f1 > f2:
        a = m1
        m1 = m2
        f1 = f2
        h *= gs
        m2 = a + gs * h
        f2 = f(m2)
    else:
        b = m2
        m2 = m1
        f2 = f1
        h *= gs
        m1 = a + (1 - gs) * h
        f1 = f(m1)
    break
print(a)
print(b)

# End your modifications above here

-1
4.562305898749054


In [11]:
gs = (np.sqrt(5) - 1) / 2
22 * (gs**3)

5.193495504995375

# Optimization (nd)

nd: grad = 0; H positive definite

# Steepest Descent

linear convergent

In [ ]:
import numpy.linalg as la
import scipy.optimize as opt
import numpy as np

def obj_func(alpha, x, s):
    # code for computing the objective function at (x+alpha*s)
    return f_of_x_plus_alpha_s

def gradient(inpu):
    # code for computing gradient
    x, y = inpu
    return np.array([x/4 - np.cos(x)*np.cos(y / np.sqrt(2)), 
                    y/4 + 1 / np.sqrt(x) * np.sin(x)*np.sin(y / np.sqrt(2))])

def steepest_descent(x_init):
    x_new = x_init
    x_prev = np.random.randn(x_init.shape[0])
    while(la.norm(x_prev - x_new) > 1e-6):
        x_prev = x_new
        s = -gradient(x_prev)
        alpha = opt.minimize_scalar(obj_func, args=(x_prev, s)).x
        x_new = x_prev + alpha*s

In [2]:
def f(inp):
    x, y = inp
    return 2 * x**2 + 14 * x* y + 2 * y**2 + 10 * np.sin(y)**2 + 4 * np.cos(x * y)

In [3]:
x0 = [-4, 2]
s0 = -1 * nd.Gradient(f)(x0)
s0

array([-19.91486597,  71.3977569 ])

In [4]:
x1 = x0 + 0.05 * s0
x1

array([-4.9957433 ,  5.56988784])

# Newton's method 

In [ ]:
import numpy as np
import numpy.linalg as la
import scipy.optimize as opt
def f(r):
    x, y = r
    return 3 +((x**2)/8) + ((y**2)/8) - np.sin(x)*np.cos((2**-0.5)*y)
    
def gradient(inpu):
    # code for computing gradient
    x, y = inpu
    return np.array([x/4 - np.cos(x)*np.cos(y / np.sqrt(2)), 
                    y/4 + 1 / np.sqrt(x) * np.sin(x)*np.sin(y / np.sqrt(2))])
                    
def hessian(inpu):
    x, y = inpu
    return np.array([[np.sin(x)*np.cos(y/np.sqrt(2)) + 1/4,
        np.cos(x)*np.sin(y / np.sqrt(2))/np.sqrt(2)], 
    [np.cos(x)*np.sin(y / np.sqrt(2))/np.sqrt(2),
    np.sin(x)*np.cos(y/np.sqrt(2)) + 1/4]])
    
def newtons(x_init, stop):
    count = 0
    x_new = x_init
    x_prev = np.random.randn(x_init.shape[0])
    while(la.norm(x_prev-x_new)>stop):
        x_prev = x_new
        s = -la.solve(hessian(x_prev), gradient(x_prev))
        x_new = x_prev + s
        count += 1
    return x_new, count
    
def steepest_descent(x_init, stop):
    count = 0
    x_new = x_init
    x_prev = np.random.randn(x_init.shape[0])
    while(la.norm(x_prev - x_new) > stop):
        x_prev = x_new
        s = -gradient(x_prev)
        alpha = opt.minimize_scalar(f, args=(x_prev, s)).x
        x_new = x_prev + alpha*s
        count += 1
    return x_new, count
    
r_newton, iteration_count_newton = newtons(r_init, stop)
r_sd, iteration_count_sd = steepest_descent(r_init, stop)



In [53]:
def f(x):
    return 4 * np.cos(x)**3

In [54]:
x0 = 0.3
x1 = x0 - nd.Gradient(f)(x0)/nd.Hessian(f)(x0)
x1

array([[-0.08254733]])