In [1]:
import numpy as np
import numpy.linalg as la

In [3]:
A = np.array([[2, 200],[4, 500], [5, 300]])
b = np.array([200, 700, 200])
c = la.lstsq(A, b, rcond=None)[0]

In [4]:
c@np.array([2, 200])

241.26984126984127

### V is eigenvectors of ATA (right)
### U is eigenvectors of AAT (left)
### A = PDP-1
### P eigenvector; D eigenvalues

## LHS normal equations 

In [51]:
t = np.array([2, 4, 6])
t_new = np.vstack((np.sin(t), np.sqrt(t))).T
t_new

array([[ 0.90929743,  1.41421356],
       [-0.7568025 ,  2.        ],
       [-0.2794155 ,  2.44948974]])

In [52]:
M = t_new.T@t_new
M

array([[ 1.47764485, -0.91208963],
       [-0.91208963, 12.        ]])

## least squares linear 

In [36]:
t = np.array([-3, 3, -0.2, 2.1])
y = np.array([-12.7, 10.9, -1, 5.1])

x1 = t.copy()
x0 = np.ones(t.shape[0])

X = np.vstack([x1, x0]).T

c = la.lstsq(X, y, rcond=None)[0]
c

array([ 3.89221487, -0.77380207])

## quadratic fit 

In [41]:
import numpy as np

t = np.array([4, -4.2, 2.1])
y = np.array([48.3, 15.9, 16])

A = np.vstack([t, t**2]).T

coeffs = la.lstsq(A, y)[0]
coeffs

<ipython-input-41-8cfd6f4a3cfc>:8: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  coeffs = la.lstsq(A, y)[0]


array([4.24728803, 1.92177718])

## least squares nonlinear

In [12]:
import numpy as np

x3 = study_time	**3
x2 = (study_time+ 1)**2
x1 = np.sqrt(study_time)
x0 = np.ones(study_time.shape[0])

X = np.vstack([x3, x2, x1, x0]).T

#coeffs = la.lstsq(X, scores)[0]

## exp fit 

In [ ]:
x1 = np.arange(population.shape[0])
x0 = np.ones(population.shape[0])

X = np.vstack([x1, x0]).T
lgy = np.log(population)

c1, lgc0 = la.lstsq(X, lgy)[0]
c0 = np.exp(lgc0)

# least squares and predict

In [ ]:
x1 = given_year
x0 = np.ones(given_year.shape[0])
X = np.vstack([x1, x0]).T

c1, c0 = la.lstsq(X, given_sales)[0]

pred_sales = pred_year * c1 + c0

## left right multiply 

In [14]:
sigma = [1, 2, 3, 4, 5]
sig_inv = la.inv(np.diag(sigma))
x = left_multiply_with_V(sig_inv@right_multiply_with_U(b.T).T)

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.2       ]])

## pinv without la 

In [20]:
sigma = np.array([1, 2, 3])
sigma_inv = np.diag(1 / sigma)
m, n = 5, 4
pinv = np.zeros((5, 4))
pinv[:sigma_inv.shape[0], :sigma_inv.shape[1]] = sigma_inv
pinv = pinv.T
pinv

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

## solve least square with svd

In [47]:
b = np.array([3, 0])
U = np.array([[1, 0], [0, -1]])
sig = [8, 0]
Vt = np.array([[-np.sqrt(3)/2, -1/2],
               [1/2, -np.sqrt(3)/2],
              ])
sig_plus = la.pinv(np.diag(sig))
x = Vt.T@sig_plus@U.T@b
x

array([-0.32475953, -0.1875    ])

## number of values 

In [44]:
r = 4
m = 74
n = 46
m * r + r + n * r

484

In [50]:
len(set([11, 7, 6, 10, 6.5, 9.5, 10]))

6